// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EmberMX_PFlowOp.rc
//
#define IDB_DEPOT_ICON 301
#define IDD_EMBERFOLLOW 301
#define IDB_INACTIVE 302
#define IDB_ACTIVE 303
#define IDB_DEPOT_MASK 305
#define IDS_CLASSNAME 306
#define IDS_CATEGORY 307
#define IDS_DESCRIPTION 308
#define IDS_PARAMETERS 309
#define IDS_EMPTY_VOXELS 310
#define IDS_OBJECTNAME 311
#define IDS_VELOCITYBLENDPERCENT 315
#define IDS_SPINBLENDPERCENT 316
#define IDS_VELOCITY_LOADER_NODE 321
#define IDC_VELOCITY_BLEND_PER_FRAME 3009
#define IDC_EMBERFOLLOW_VELOCITYBLEND_EDIT 3009
#define IDC_VELOCITY_BLEND_PER_FRAME_SPIN 3010
#define IDC_EMBERFOLLOW_VELOCITYBLEND_SPIN 3010
#define IDC_STATIC3 3011
#define IDC_EMBERFOLLOW_ORIENTATIONBLEND_EDIT 3012
#define IDC_EMBERFOLLOW_ORIENTATIONBLEND_SPIN 3013
#define IDC_STATIC4 3014
#define IDC_EMBERFOLLOW_SPINBLEND_EDIT 3015
#define IDC_EMBERFOLLOW_SPINBLEND_SPIN 3016
#define IDC_STATIC5 3017
#define IDC_EMBERFOLLOW_SCALEBLEND_EDIT 3018
#define IDC_EMBERFOLLOW_SCALEBLEND_SPIN 3019
#define IDC_STATIC6 3020
#define IDC_VELOCITY_LOADER_NODE 3023
#define IDC_EMBERFOLLOW_CONTEXTMENU 3025
#define IDC_EMBERFOLLOW_VELOCITY_COMBO 3027
#define IDC_STATIC10 3028
#define IDC_EMBERFOLLOW_ORIENTATION_COMBO 3029
#define IDC_EMBERFOLLOW_SPIN_COMBO 3030
#define IDC_EMBERFOLLOW_SCALE_COMBO 3031
#define IDC_EMBERFOLLOW_SELECTED_COMBO 3032
#define IDC_EMBERFOLLOW_MTLID_COMBO 3033
#define IDC_EMBERFOLLOW_SCRIPTINT_COMBO 3034
#define IDC_EMBERFOLLOW_SCRIPTFLOAT_COMBO 3035
#define IDC_EMBERFOLLOW_SCRIPTVECTOR_COMBO 3036
#define IDC_EMBERFOLLOW_VERTEXCOLOR_COMBO 3037
#define IDC_EMBERFOLLOW_SELECTED_COMBO3 3038
#define IDC_EMBERFOLLOW_TEXTURECOORD_COMBO 3038
#define IDC_STATIC -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 308
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 3030
#define _APS_NEXT_SYMED_VALUE 302
#endif
#endif
