// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Genome.rc
//
#define IDS_LIBDESCRIPTION 1
#define IDS_CATEGORY 2
#define IDS_CLASS_NAME 3
#define IDS_PARAMETERS 4
#define IDS_MESH_ITERATION_PATTERN 5
#define IDS_MAGMAMODIFIER_TITLE 6
#define IDS_GENOME_MAINROLLOUT_TITLE 6
#define IDS_CAMERA_PARAMETERS 7
#define IDS_PICK_CAMERA_PROMPT 8
#define IDS_GENOME_MAGMAHOLDER 9
#define IDS_GENOME_REMOVEDEGENERATE 10
#define IDS_GENOME_CLAMPSELECTION 11
#define IDS_GENOME_ABOUTROLLOUT_TITLE 12
#define IDD_MAGMAMODIFIER 401
#define IDD_GENOME 401
#define IDD_GENOME_ABOUT 405
#define IDC_MAGMAMODIFIER_OPEN_BUTTON 4012
#define IDC_MAGMAMODIFIER_AUTORENAME_CHECK 4013
#define IDC_MESH_ITERATION_PATTERN 4014
#define IDC_MAGMAMODIFIER_REMOVEDEGENERATE_CHECK 4015
#define IDC_MAGMAMODIFIER_CLAMPVERTSELECTION_CHECK 4017
#define IDC_MAGMAMODIFIER_AUTOUPDATE_CHECK 4018
#define IDC_GENOMEABOUT_OPENHELP_BUTTON 4030
#define IDC_GENOMEABOUT_VERSION_STATIC 4032
#define IDC_GENOMEABOUT_OPENHELP_BUTTON2 4033
#define IDC_GENOMEABOUT_OPENLOG_BUTTON 4033
#define IDC_BUTTON1 4034
#define IDC_GENOME_EDITORCONTEXT_BUTTON 4034
#define IDC_MAGMAMODIFIER_ITERATIONS_EDIT 4035
#define IDC_CUSTOM2 4036
#define IDC_MAGMAMODIFIER_ITERATIONS_SPIN 4036

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 406
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 4037
#define _APS_NEXT_SYMED_VALUE 401
#endif
#endif
